import { getSessionFromRequest, unauthorized } from "@/features/auth/server/session";
import { authzErrorResponse } from "@/features/workspaces/server/authz";
import { extensionTaskBridge, installWorkspaceExtension, listTaskSlotExtensions, listWorkspaceExtensions, removeWorkspaceExtension } from "./repository";
import { EXTENSION_SLOTS, isExtensionScope } from "../types";
const bad=(error:string)=>Response.json({error},{status:400});
export async function listExtensions(request:Request,workspaceId:string){const s=await getSessionFromRequest(request);if(!s)return unauthorized();try{return Response.json(await listWorkspaceExtensions(s.user.id,workspaceId));}catch(e){return authzErrorResponse(e);}}
export async function installExtension(request:Request,workspaceId:string){const s=await getSessionFromRequest(request);if(!s)return unauthorized();const body=await request.json().catch(()=>null);if(!body)return bad("An extension manifest is required");try{return Response.json(await installWorkspaceExtension(s.user.id,workspaceId,body),{status:201});}catch(e){return authzErrorResponse(e);}}
export async function deleteExtension(request:Request,workspaceId:string,id:string){const s=await getSessionFromRequest(request);if(!s)return unauthorized();const parsed=Number(id);if(!Number.isInteger(parsed))return bad("Invalid extension id");try{await removeWorkspaceExtension(s.user.id,workspaceId,parsed);return new Response(null,{status:204});}catch(e){return authzErrorResponse(e);}}
export async function taskPanels(request:Request,taskId:number){const s=await getSessionFromRequest(request);if(!s)return unauthorized();if(!Number.isInteger(taskId))return bad("Invalid task id");const slot=new URL(request.url).searchParams.get("slot")??"task_panel";if(!(EXTENSION_SLOTS as readonly string[]).includes(slot))return bad("Invalid extension slot");try{return Response.json(await listTaskSlotExtensions(s.user.id,taskId,slot as import("../types").ExtensionSlot));}catch(e){return authzErrorResponse(e);}}
export async function taskBridge(request:Request,taskId:number,extensionId:number){const s=await getSessionFromRequest(request);if(!s)return unauthorized();if(!Number.isInteger(taskId)||!Number.isInteger(extensionId))return bad("Invalid extension or task id");const scope=new URL(request.url).searchParams.get("scope")??"task";if(!isExtensionScope(scope))return bad("Invalid extension scope");try{return Response.json(await extensionTaskBridge(s.user.id,taskId,extensionId,scope));}catch(e){return authzErrorResponse(e);}}
