import { query, queryOne } from "@/shared/db/client";
import { AuthzError, requireTaskRole, requireWorkspaceRole } from "@/features/workspaces/server/authz";
import { EXTENSION_SLOTS, readManifest, type ExtensionSlot, type WorkspaceExtension } from "../types";
const COLUMNS = `id,workspace_id AS "workspaceId",name,url,capabilities,slots,installed_by AS "installedBy",created_at AS "createdAt",updated_at AS "updatedAt"`;
export async function listWorkspaceExtensions(userId: string, workspaceId: string): Promise<WorkspaceExtension[]> { await requireWorkspaceRole(userId, workspaceId, "viewer"); const rows = await query<WorkspaceExtension & { manifest: unknown }>(`SELECT ${COLUMNS},manifest FROM workspace_extension WHERE workspace_id=$1 ORDER BY name`, [workspaceId]); return rows.map(({ manifest, ...row }) => ({ ...row, ...(readManifest(manifest) ?? { name: row.name, url: row.url, capabilities: row.capabilities, slots: row.slots }) })); }
export async function installWorkspaceExtension(userId: string, workspaceId: string, manifestValue: unknown): Promise<WorkspaceExtension> { await requireWorkspaceRole(userId, workspaceId, "owner"); const manifest = readManifest(manifestValue); if (!manifest) throw new AuthzError("conflict", "Invalid extension manifest"); return (await queryOne<WorkspaceExtension>(`INSERT INTO workspace_extension(workspace_id,name,manifest,url,capabilities,slots,installed_by) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(workspace_id,name) DO UPDATE SET manifest=EXCLUDED.manifest,url=EXCLUDED.url,capabilities=EXCLUDED.capabilities,slots=EXCLUDED.slots,installed_by=EXCLUDED.installed_by,updated_at=now() RETURNING ${COLUMNS}`,[workspaceId,manifest.name,JSON.stringify(manifest),manifest.url,manifest.capabilities,manifest.slots,userId]))!; }
export async function removeWorkspaceExtension(userId: string, workspaceId: string, id: number): Promise<void> { await requireWorkspaceRole(userId, workspaceId, "owner"); const row=await queryOne<{id:number}>(`DELETE FROM workspace_extension WHERE id=$1 AND workspace_id=$2 RETURNING id`,[id,workspaceId]);if(!row)throw new AuthzError("not_found","Extension not found"); }
export async function listTaskSlotExtensions(userId: string, taskId: number, slot: ExtensionSlot): Promise<WorkspaceExtension[]> { const { workspaceId }=await requireTaskRole(userId,taskId,"viewer"); const rows=await query<WorkspaceExtension & {manifest:unknown}>(`SELECT ${COLUMNS},manifest FROM workspace_extension WHERE workspace_id=$1 AND $2=ANY(slots) ORDER BY name`,[workspaceId,slot]);return rows.map(({manifest,...row})=>({...row,...(readManifest(manifest)??{name:row.name,url:row.url,capabilities:row.capabilities,slots:row.slots})})); }
export async function extensionTaskBridge(userId: string, taskId: number, extensionId: number): Promise<{ task: { id:number; title:string; description:string|null; dueDate:string|null; startDate:string|null } }> { const {workspaceId}=await requireTaskRole(userId,taskId,"viewer");const extension=await queryOne<{capabilities:string[]}>(`SELECT capabilities FROM workspace_extension WHERE id=$1 AND workspace_id=$2`,[extensionId,workspaceId]);if(!extension)throw new AuthzError("not_found","Extension not found");if(!extension.capabilities.includes("task.read"))throw new AuthzError("forbidden","Extension was not granted task.read");const task=await queryOne<{id:number;title:string;description:string|null;dueDate:string|null;startDate:string|null}>(`SELECT id,title,description,due_date AS "dueDate",start_date AS "startDate" FROM task WHERE id=$1`,[taskId]);if(!task)throw new AuthzError("not_found","Task not found");return {task}; }
