import { getSessionFromRequest, unauthorized } from "@/features/auth/server/session";
import { authzErrorResponse } from "@/features/workspaces/server/authz";
import { FormSubmitError } from "@/features/forms/server/repository";
import { publicRateLimit } from "@/shared/lib/rate-limit";
import { getPublicBoard,getPublicForm,getSharedBoard,grantObjectShare,listObjectShares,listPublicLinks,mintPublicLink,revokeObjectShare,revokePublicLink,submitPublicForm,type ShareSubject } from "./repository";
const bad=(error:string)=>Response.json({error},{status:400}); const subjects=new Set(["doc","board","form","view"]);
/** Pulls a validated ?subjectType=&subjectId= pair off a list request, or null. */
function subjectParams(request:Request){const u=new URL(request.url);const subjectType=u.searchParams.get("subjectType");const subjectId=u.searchParams.get("subjectId");if(!subjectType||!subjects.has(subjectType)||!subjectId)return null;return{subjectType:subjectType as ShareSubject,subjectId};}
export async function mint(request:Request){const s=await getSessionFromRequest(request);if(!s)return unauthorized();const p=await request.json().catch(()=>null);if(!p||!subjects.has(p.subjectType)||typeof p.subjectId!=="string"||!["read","submit"].includes(p.scope))return bad("Invalid share link");try{return Response.json(await mintPublicLink(s.user.id,p.subjectType as ShareSubject,p.subjectId,p.scope,p.expiresAt),{status:201});}catch(e){return authzErrorResponse(e);}}
export async function revoke(request:Request,id:string){const s=await getSessionFromRequest(request);if(!s)return unauthorized();const linkId=Number(id);if(!Number.isInteger(linkId))return bad("Invalid public link id");try{await revokePublicLink(s.user.id,linkId);return new Response(null,{status:204});}catch(e){return authzErrorResponse(e);}}
export async function grant(request:Request){const s=await getSessionFromRequest(request);if(!s)return unauthorized();const p=await request.json().catch(()=>null);if(!p||!["doc","board","form"].includes(p.subjectType)||typeof p.subjectId!=="string"||typeof p.userId!=="string"||typeof p.canEdit!=="boolean")return bad("Invalid object share");try{await grantObjectShare(s.user.id,p.subjectType,p.subjectId,p.userId,p.canEdit);return new Response(null,{status:204});}catch(e){return authzErrorResponse(e);}}
export async function ungrant(request:Request){const s=await getSessionFromRequest(request);if(!s)return unauthorized();const p=await request.json().catch(()=>null);if(!p||!["doc","board","form"].includes(p.subjectType)||typeof p.subjectId!=="string"||typeof p.userId!=="string")return bad("Invalid object share");try{await revokeObjectShare(s.user.id,p.subjectType,p.subjectId,p.userId);return new Response(null,{status:204});}catch(e){return authzErrorResponse(e);}}
export async function listLinks(request:Request){const s=await getSessionFromRequest(request);if(!s)return unauthorized();const p=subjectParams(request);if(!p)return bad("Invalid share subject");try{return Response.json(await listPublicLinks(s.user.id,p.subjectType,p.subjectId));}catch(e){return authzErrorResponse(e);}}
export async function listShares(request:Request){const s=await getSessionFromRequest(request);if(!s)return unauthorized();const p=subjectParams(request);if(!p)return bad("Invalid share subject");try{return Response.json(await listObjectShares(s.user.id,p.subjectType,p.subjectId));}catch(e){return authzErrorResponse(e);}}
export async function publicBoard(request:Request,token:string){const limited=publicRateLimit(request,token);if(limited)return limited;try{return Response.json(await getPublicBoard(token),{headers:{"Cache-Control":"no-store"}});}catch(e){return authzErrorResponse(e);}}
export async function publicForm(request:Request,token:string){const limited=publicRateLimit(request,token);if(limited)return limited;try{return Response.json(await getPublicForm(token),{headers:{"Cache-Control":"no-store"}});}catch(e){return authzErrorResponse(e);}}
/** Tighter than the reads: a submit writes a task, so the sustained rate is one every few seconds per IP+token. */
export async function publicFormSubmit(request:Request,token:string){const limited=publicRateLimit(request,token,{capacity:5,refillPerSecond:0.2});if(limited)return limited;const p=await request.json().catch(()=>null);const answers=(p as {answers?:unknown}|null)?.answers;if(!Array.isArray(answers)||answers.some((a)=>typeof a!=="string"))return bad("answers must be an array of strings");try{await submitPublicForm(token,answers as string[]);return Response.json({ok:true},{status:201});}catch(e){if(e instanceof FormSubmitError)return bad(e.message);return authzErrorResponse(e);}}
export async function sharedBoard(request:Request,id:string){const s=await getSessionFromRequest(request);if(!s)return unauthorized();const boardId=Number(id);if(!Number.isInteger(boardId))return bad("Invalid board id");try{return Response.json(await getSharedBoard(s.user.id,boardId));}catch(e){return authzErrorResponse(e);}}
