import { getSessionFromRequest, unauthorized } from "@/features/auth/server/session";
import { authzErrorResponse } from "@/features/workspaces/server/authz";
import { getPublicBoard,getSharedBoard,grantObjectShare,mintPublicLink,revokeObjectShare,revokePublicLink,type ShareSubject } from "./repository";
const bad=(error:string)=>Response.json({error},{status:400}); const subjects=new Set(["doc","board","form","view"]);
export async function mint(request:Request){const s=await getSessionFromRequest(request);if(!s)return unauthorized();const p=await request.json().catch(()=>null);if(!p||!subjects.has(p.subjectType)||typeof p.subjectId!=="string"||!["read","submit"].includes(p.scope))return bad("Invalid share link");try{return Response.json(await mintPublicLink(s.user.id,p.subjectType as ShareSubject,p.subjectId,p.scope,p.expiresAt),{status:201});}catch(e){return authzErrorResponse(e);}}
export async function revoke(request:Request,id:string){const s=await getSessionFromRequest(request);if(!s)return unauthorized();const linkId=Number(id);if(!Number.isInteger(linkId))return bad("Invalid public link id");try{await revokePublicLink(s.user.id,linkId);return new Response(null,{status:204});}catch(e){return authzErrorResponse(e);}}
export async function grant(request:Request){const s=await getSessionFromRequest(request);if(!s)return unauthorized();const p=await request.json().catch(()=>null);if(!p||!["doc","board","form"].includes(p.subjectType)||typeof p.subjectId!=="string"||typeof p.userId!=="string"||typeof p.canEdit!=="boolean")return bad("Invalid object share");try{await grantObjectShare(s.user.id,p.subjectType,p.subjectId,p.userId,p.canEdit);return new Response(null,{status:204});}catch(e){return authzErrorResponse(e);}}
export async function ungrant(request:Request){const s=await getSessionFromRequest(request);if(!s)return unauthorized();const p=await request.json().catch(()=>null);if(!p||!["doc","board","form"].includes(p.subjectType)||typeof p.subjectId!=="string"||typeof p.userId!=="string")return bad("Invalid object share");try{await revokeObjectShare(s.user.id,p.subjectType,p.subjectId,p.userId);return new Response(null,{status:204});}catch(e){return authzErrorResponse(e);}}
export async function publicBoard(_request:Request,token:string){try{return Response.json(await getPublicBoard(token),{headers:{"Cache-Control":"no-store"}});}catch(e){return authzErrorResponse(e);}}
export async function sharedBoard(request:Request,id:string){const s=await getSessionFromRequest(request);if(!s)return unauthorized();const boardId=Number(id);if(!Number.isInteger(boardId))return bad("Invalid board id");try{return Response.json(await getSharedBoard(s.user.id,boardId));}catch(e){return authzErrorResponse(e);}}
