import crypto from "node:crypto";
import { query, queryOne } from "@/shared/db/client";
import { AuthzError, requireWorkspaceRole } from "@/features/workspaces/server/authz";
export type ShareSubject="doc"|"board"|"form"|"view";
async function workspaceFor(subject:ShareSubject,id:string){
  const sql=subject==="doc"?`SELECT workspace_id AS "workspaceId" FROM doc WHERE id=$1`:subject==="board"?`SELECT workspace_id AS "workspaceId" FROM board WHERE id=$1`:subject==="view"?`SELECT workspace_id AS "workspaceId" FROM saved_view WHERE id=$1`:`SELECT b.workspace_id AS "workspaceId" FROM ${subject} x JOIN board b ON b.id=x.board_id WHERE x.id=$1`;
  const row=await queryOne<{workspaceId:string}>(sql,[id]); if(!row)throw new AuthzError("not_found","Share subject not found"); return row.workspaceId;
}
export async function mintPublicLink(userId:string,subject:ShareSubject,subjectId:string,scope:"read"|"submit",expiresAt?:string|null){const workspaceId=await workspaceFor(subject,subjectId);await requireWorkspaceRole(userId,workspaceId,"admin");const token=crypto.randomBytes(32).toString("base64url");return (await queryOne<{id:number;token:string}>(`INSERT INTO public_link(subject_type,subject_id,token,scope,expires_at,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,token`,[subject,subjectId,token,scope,expiresAt??null,userId]))!;}
export async function revokePublicLink(userId:string,id:number){const row=await queryOne<{subjectType:ShareSubject;subjectId:string}>(`SELECT subject_type AS "subjectType",subject_id AS "subjectId" FROM public_link WHERE id=$1`,[id]);if(!row)throw new AuthzError("not_found","Public link not found");await requireWorkspaceRole(userId,await workspaceFor(row.subjectType,row.subjectId),"admin");await query(`DELETE FROM public_link WHERE id=$1`,[id]);}
export async function grantObjectShare(userId:string,subject:Exclude<ShareSubject,"view">,subjectId:string,targetUserId:string,canEdit:boolean){const workspaceId=await workspaceFor(subject,subjectId);await requireWorkspaceRole(userId,workspaceId,"admin");const member=await queryOne<{id:string}>(`SELECT user_id AS id FROM workspace_member WHERE workspace_id=$1 AND user_id=$2`,[workspaceId,targetUserId]);if(!member)throw new AuthzError("not_found","Guest not found in this workspace");await query(`INSERT INTO object_share(subject_type,subject_id,user_id,can_edit) VALUES($1,$2,$3,$4) ON CONFLICT(subject_type,subject_id,user_id) DO UPDATE SET can_edit=EXCLUDED.can_edit`,[subject,subjectId,targetUserId,canEdit]);}
export async function revokeObjectShare(userId:string,subject:Exclude<ShareSubject,"view">,subjectId:string,targetUserId:string){const workspaceId=await workspaceFor(subject,subjectId);await requireWorkspaceRole(userId,workspaceId,"admin");await query(`DELETE FROM object_share WHERE subject_type=$1 AND subject_id=$2 AND user_id=$3`,[subject,subjectId,targetUserId]);}
export async function getPublicBoard(token:string){const board=await queryOne<{id:number;name:string}>(`SELECT b.id,b.name FROM public_link p JOIN board b ON b.id=p.subject_id::int WHERE p.token=$1 AND p.subject_type='board' AND p.scope='read' AND (p.expires_at IS NULL OR p.expires_at>now())`,[token]);if(!board)throw new AuthzError("not_found","Public board not found");const columns=await query<{id:number;title:string;position:number}>(`SELECT id,title,position FROM board_column WHERE board_id=$1 ORDER BY position,id`,[board.id]);const tasks=await query<{id:number;columnId:number;title:string;description:string}>(`SELECT t.id,t.column_id AS "columnId",t.title,t.description FROM task t WHERE t.column_id IN(SELECT id FROM board_column WHERE board_id=$1) AND t.parent_id IS NULL ORDER BY t.position`,[board.id]);return{...board,columns,tasks};}
export async function getSharedBoard(userId:string,boardId:number){const shared=await queryOne<{canEdit:boolean}>(`SELECT can_edit AS "canEdit" FROM object_share WHERE subject_type='board' AND subject_id=$1 AND user_id=$2`,[String(boardId),userId]);if(!shared)throw new AuthzError("not_found","Board not found");const columns=await query<{id:number;title:string;position:number}>(`SELECT id,title,position FROM board_column WHERE board_id=$1 ORDER BY position,id`,[boardId]);if(!columns.length)throw new AuthzError("not_found","Board not found");const board=await queryOne<{id:number;name:string}>(`SELECT id,name FROM board WHERE id=$1`,[boardId]);const tasks=await query<{id:number;columnId:number;title:string;description:string}>(`SELECT id,column_id AS "columnId",title,description FROM task WHERE column_id=ANY($1) AND parent_id IS NULL ORDER BY position`,[columns.map(c=>c.id)]);return{...board!,columns,tasks,canEdit:shared.canEdit};}
