import { randomUUID } from "node:crypto";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { ensurePersonalWorkspace, getDefaultBoard } from "@/features/workspaces/server/repository";
import { pool, query } from "@/shared/db/client";
import { addChannelMember, createChannel, listChannelMembers, listChannels, listMessages, markChannelSeen, openDm, postMessage, removeChannelMember } from "./repository";

describe("chat (db)", () => {
  const users: string[] = []; let alice: string; let bob: string; let workspaceId: string;
  beforeAll(async () => { alice=`chat-a-${randomUUID()}`;bob=`chat-b-${randomUUID()}`;users.push(alice,bob);for(const [id,name] of [[alice,"Alice"],[bob,"Bob"]])await query(`INSERT INTO "user"(id,name,email,"emailVerified") VALUES($1,$2,$3,true)`,[id,name,`${id}@test`]);await ensurePersonalWorkspace(alice,"Alice");const board=(await getDefaultBoard(alice))!;workspaceId=board.workspaceId;await query(`INSERT INTO workspace_member(workspace_id,user_id,role) VALUES($1,$2,'member')`,[workspaceId,bob]); });
  afterAll(async()=>{await query(`DELETE FROM workspace w WHERE EXISTS(SELECT 1 FROM workspace_member m WHERE m.workspace_id=w.id AND m.user_id=ANY($1))`,[users]);await query(`DELETE FROM "user" WHERE id=ANY($1)`,[users]);await pool.end();});
  it("shows workspace channels and persists a thread",async()=>{const channel=await createChannel(alice,workspaceId,"general");expect((await listChannels(bob,workspaceId)).map(c=>c.id)).toContain(channel.id);const root=await postMessage(alice,channel.id,"hello");await postMessage(bob,channel.id,"reply",root.id);expect((await listMessages(alice,channel.id)).map(m=>m.parentId)).toEqual([null,root.id]);});
  it("hides private channels from nonmembers",async()=>{const secret=await createChannel(alice,workspaceId,"secret",true);expect((await listChannels(bob,workspaceId)).map(c=>c.id)).not.toContain(secret.id);await expect(listMessages(bob,secret.id)).rejects.toThrow(/not found/i);});
  it("resolves author display names",async()=>{const channel=await createChannel(alice,workspaceId,"names");await postMessage(alice,channel.id,"hi from alice");await postMessage(bob,channel.id,"hi from bob");expect((await listMessages(bob,channel.id)).map(m=>m.authorName)).toEqual(["Alice","Bob"]);});
  it("keeps a reply in its own channel, one level deep",async()=>{const a=await createChannel(alice,workspaceId,"thread-a");const b=await createChannel(alice,workspaceId,"thread-b");const root=await postMessage(alice,a.id,"root");await expect(postMessage(bob,b.id,"cross",root.id)).rejects.toThrow(/not in this channel/i);const reply=await postMessage(bob,a.id,"reply",root.id);await expect(postMessage(alice,a.id,"deep",reply.id)).rejects.toThrow(/replies of its own/i);});
  it("logs a chat mention activity only when someone is named",async()=>{const channel=await createChannel(alice,workspaceId,"mentions");await postMessage(alice,channel.id,"nothing to see");await postMessage(alice,channel.id,"@Bob please look at this");const rows=await query<{action:string;after:{channelName:string;mentions:string[];body:string}}>(`SELECT action, after FROM activity_log WHERE workspace_id=$1 AND action='chat.mentioned'`,[workspaceId]);expect(rows).toHaveLength(1);expect(rows[0].after.mentions).toEqual([bob]);expect(rows[0].after.channelName).toBe("mentions");expect(rows[0].after.body).toBe("@Bob please look at this");});
  it("creates a DM once and reuses it from either side",async()=>{const dm=await openDm(alice,workspaceId,bob);expect(dm.isPrivate).toBe(true);expect(dm.name.startsWith("dm:")).toBe(true);expect((await openDm(alice,workspaceId,bob)).id).toBe(dm.id);expect((await openDm(bob,workspaceId,alice)).id).toBe(dm.id);expect((await listChannelMembers(bob,dm.id)).map(m=>m.userId).sort()).toEqual([alice,bob].sort());await expect(openDm(alice,workspaceId,alice)).rejects.toThrow(/two people/i);});
  it("manages private-channel members, member-gated, never below one",async()=>{const secret=await createChannel(alice,workspaceId,"roster",true);await expect(addChannelMember(bob,secret.id,bob)).rejects.toThrow(/not found/i);await addChannelMember(alice,secret.id,bob);expect((await listChannelMembers(bob,secret.id)).map(m=>m.userId)).toContain(bob);await removeChannelMember(bob,secret.id,alice);await expect(removeChannelMember(bob,secret.id,bob)).rejects.toThrow(/last member/i);const open=await createChannel(alice,workspaceId,"open-roster");await expect(addChannelMember(alice,open.id,bob)).rejects.toThrow(/no member list/i);});
  it("tracks unread per reader and clears it on seen",async()=>{const channel=await createChannel(alice,workspaceId,"unread");await postMessage(alice,channel.id,"news");const forBob=(await listChannels(bob,workspaceId)).find(c=>c.id===channel.id)!;expect(forBob.hasUnread).toBe(true);const forAlice=(await listChannels(alice,workspaceId)).find(c=>c.id===channel.id)!;expect(forAlice.hasUnread).toBe(false);await markChannelSeen(bob,channel.id);expect((await listChannels(bob,workspaceId)).find(c=>c.id===channel.id)!.hasUnread).toBe(false);await postMessage(alice,channel.id,"more news");expect((await listChannels(bob,workspaceId)).find(c=>c.id===channel.id)!.hasUnread).toBe(true);});
});
