import { getSessionFromRequest, unauthorized } from "@/features/auth/server/session";
import { authzErrorResponse } from "@/features/workspaces/server/authz";
import { addChannelMember, createChannel, listChannelMembers, listChannels, listMessages, markChannelSeen, openDm, postMessage, removeChannelMember } from "./repository";
const bad=(error:string)=>Response.json({error},{status:400});
export async function channels(request:Request,workspaceId:string){const s=await getSessionFromRequest(request);if(!s)return unauthorized();try{return Response.json(await listChannels(s.user.id,workspaceId));}catch(e){return authzErrorResponse(e);}}
export async function create(request:Request,workspaceId:string){const s=await getSessionFromRequest(request);if(!s)return unauthorized();const p=await request.json().catch(()=>null);if(!p||typeof p.name!=="string"||!p.name.trim())return bad("name is required");if(p.isPrivate!==undefined&&typeof p.isPrivate!=="boolean")return bad("isPrivate must be a boolean");try{return Response.json(await createChannel(s.user.id,workspaceId,p.name,p.isPrivate===true),{status:201});}catch(e){return authzErrorResponse(e);}}
export async function dm(request:Request,workspaceId:string){const s=await getSessionFromRequest(request);if(!s)return unauthorized();const p=await request.json().catch(()=>null);if(!p||typeof p.userId!=="string"||!p.userId)return bad("userId is required");try{return Response.json(await openDm(s.user.id,workspaceId,p.userId),{status:201});}catch(e){return authzErrorResponse(e);}}
export async function messages(request:Request,id:string){const s=await getSessionFromRequest(request);if(!s)return unauthorized();const channelId=Number(id);if(!Number.isInteger(channelId))return bad("Invalid channel id");try{return Response.json(await listMessages(s.user.id,channelId));}catch(e){return authzErrorResponse(e);}}
export async function post(request:Request,id:string){const s=await getSessionFromRequest(request);if(!s)return unauthorized();const channelId=Number(id);const p=await request.json().catch(()=>null);if(!Number.isInteger(channelId)||!p||typeof p.body!=="string"||!p.body.trim())return bad("body is required");if(p.parentId!==undefined&&p.parentId!==null&&!Number.isInteger(p.parentId))return bad("parentId must be an integer or null");try{return Response.json(await postMessage(s.user.id,channelId,p.body,p.parentId),{status:201});}catch(e){return authzErrorResponse(e);}}
export async function members(request:Request,id:string){const s=await getSessionFromRequest(request);if(!s)return unauthorized();const channelId=Number(id);if(!Number.isInteger(channelId))return bad("Invalid channel id");try{return Response.json(await listChannelMembers(s.user.id,channelId));}catch(e){return authzErrorResponse(e);}}
export async function addMember(request:Request,id:string){const s=await getSessionFromRequest(request);if(!s)return unauthorized();const channelId=Number(id);const p=await request.json().catch(()=>null);if(!Number.isInteger(channelId)||!p||typeof p.userId!=="string"||!p.userId)return bad("userId is required");try{await addChannelMember(s.user.id,channelId,p.userId);return new Response(null,{status:204});}catch(e){return authzErrorResponse(e);}}
export async function removeMember(request:Request,id:string,userId:string){const s=await getSessionFromRequest(request);if(!s)return unauthorized();const channelId=Number(id);if(!Number.isInteger(channelId)||!userId)return bad("Invalid channel id");try{await removeChannelMember(s.user.id,channelId,userId);return new Response(null,{status:204});}catch(e){return authzErrorResponse(e);}}
export async function seen(request:Request,id:string){const s=await getSessionFromRequest(request);if(!s)return unauthorized();const channelId=Number(id);if(!Number.isInteger(channelId))return bad("Invalid channel id");try{await markChannelSeen(s.user.id,channelId);return new Response(null,{status:204});}catch(e){return authzErrorResponse(e);}}
