import { query, queryOne } from "@/shared/db/client";
import { AuthzError, requireWorkspaceRole } from "@/features/workspaces/server/authz";
import type { Channel, ChatMessage } from "../types";

const CHANNEL = `id, workspace_id AS "workspaceId", name, is_private AS "isPrivate", created_by AS "createdBy", created_at AS "createdAt"`;
export async function listChannels(userId: string, workspaceId: string): Promise<Channel[]> { await requireWorkspaceRole(userId, workspaceId, "viewer"); return query<Channel>(`SELECT ${CHANNEL} FROM channel c WHERE c.workspace_id=$1 AND (NOT c.is_private OR EXISTS (SELECT 1 FROM channel_member cm WHERE cm.channel_id=c.id AND cm.user_id=$2)) ORDER BY c.name`, [workspaceId,userId]); }
export async function createChannel(userId: string, workspaceId: string, name: string, isPrivate=false): Promise<Channel> { await requireWorkspaceRole(userId,workspaceId,"member"); const row=await queryOne<Channel>(`INSERT INTO channel (workspace_id,name,is_private,created_by) VALUES ($1,$2,$3,$4) RETURNING ${CHANNEL}`,[workspaceId,name.trim(),isPrivate,userId]); if (!row) throw new Error("Could not create channel"); await query(`INSERT INTO channel_member (channel_id,user_id) VALUES ($1,$2)`,[row.id,userId]); return row; }
async function access(userId:string, channelId:number, write=false) { const row=await queryOne<{workspaceId:string;isPrivate:boolean;member:boolean}>(`SELECT c.workspace_id AS "workspaceId",c.is_private AS "isPrivate",EXISTS(SELECT 1 FROM channel_member cm WHERE cm.channel_id=c.id AND cm.user_id=$2) AS member FROM channel c WHERE c.id=$1`,[channelId,userId]); if(!row) throw new AuthzError("not_found","Channel not found"); await requireWorkspaceRole(userId,row.workspaceId,write?"member":"viewer"); if(row.isPrivate&&!row.member) throw new AuthzError("not_found","Channel not found"); }
export async function listMessages(userId:string,channelId:number):Promise<ChatMessage[]> { await access(userId,channelId); return query<ChatMessage>(`SELECT id,channel_id AS "channelId",author_id AS "authorId",body,parent_id AS "parentId",created_at AS "createdAt" FROM chat_message WHERE channel_id=$1 ORDER BY created_at ASC`,[channelId]); }
export async function postMessage(userId:string,channelId:number,body:string,parentId?:number|null):Promise<ChatMessage>{ await access(userId,channelId,true); const row=await queryOne<ChatMessage>(`INSERT INTO chat_message(channel_id,author_id,body,parent_id) VALUES($1,$2,$3,$4) RETURNING id,channel_id AS "channelId",author_id AS "authorId",body,parent_id AS "parentId",created_at AS "createdAt"`,[channelId,userId,body.trim(),parentId??null]); return row!; }
