import { getSessionFromRequest, unauthorized } from "@/features/auth/server/session";
import { authzErrorResponse } from "@/features/workspaces/server/authz";
import { linkGoogleDriveFile, listTaskIntegrationLinks, syncGoogleCalendar } from "./google";
import { linkMicrosoftDriveItem, syncMicrosoftCalendar } from "./microsoft";

const bad = (error: string) => Response.json({ error }, { status: 400 });
export async function listTaskLinks(request: Request, taskId: number) { const session = await getSessionFromRequest(request); if (!session) return unauthorized(); if (!Number.isInteger(taskId)) return bad("Invalid task id"); try { return Response.json(await listTaskIntegrationLinks(session.user.id, taskId)); } catch (error) { return authzErrorResponse(error); } }
export async function addGoogleDriveLink(request: Request, taskId: number) { const session = await getSessionFromRequest(request); if (!session) return unauthorized(); const body = await request.json().catch(() => null) as { url?: unknown } | null; if (!Number.isInteger(taskId) || !body || typeof body.url !== "string") return bad("A Google Drive URL is required"); try { return Response.json(await linkGoogleDriveFile(session.user.id, taskId, body.url), { status: 201 }); } catch (error) { return authzErrorResponse(error); } }
export async function syncGoogleTaskCalendar(request: Request, taskId: number) { const session = await getSessionFromRequest(request); if (!session) return unauthorized(); if (!Number.isInteger(taskId)) return bad("Invalid task id"); try { return Response.json(await syncGoogleCalendar(session.user.id, taskId)); } catch (error) { return authzErrorResponse(error); } }
export async function addMicrosoftDriveLink(request: Request, taskId: number) { const session = await getSessionFromRequest(request); if (!session) return unauthorized(); const body = await request.json().catch(() => null) as { url?: unknown } | null; if (!Number.isInteger(taskId) || !body || typeof body.url !== "string") return bad("A OneDrive or SharePoint URL is required"); try { return Response.json(await linkMicrosoftDriveItem(session.user.id, taskId, body.url), { status: 201 }); } catch (error) { return authzErrorResponse(error); } }
export async function syncMicrosoftTaskCalendar(request: Request, taskId: number) { const session = await getSessionFromRequest(request); if (!session) return unauthorized(); if (!Number.isInteger(taskId)) return bad("Invalid task id"); try { return Response.json(await syncMicrosoftCalendar(session.user.id, taskId)); } catch (error) { return authzErrorResponse(error); } }
